lesson6
KochevniKXXI/h-h-school pull request #5
Opened 2023-11-12 18:58 UTC by KochevniKXXI

2023-11-12 19:16 UTC, DmitriyTSt requested changes

2023-11-12 19:16 UTC, DmitriyTSt commented on Lesson_6_Zemskov/app/src/main/java/hh/school/lesson_6_zemskov/MainActivity.kt
> +        binding.toolbar.title =
легче в каждом фрагменте иметь свой тулбар

2023-11-12 19:16 UTC, DmitriyTSt commented on Lesson_6_Zemskov/app/src/main/java/hh/school/lesson_6_zemskov/MainActivity.kt
> +    fun addMenu(
такое надо закрывать интерфейсом, а не обращаться к MainActivity, вдруг фрагменты будут лежать в другой, ну а вообще лучше делать тулбары во фрагментах

2023-11-12 19:16 UTC, DmitriyTSt commented on Lesson_6_Zemskov/app/src/main/java/hh/school/lesson_6_zemskov/PageFragment.kt
> +    private var paramUrl: String? = null
а можно `private val paramUrl by lazy { arguments.getString(ARG_URL) }`

2023-11-12 19:16 UTC, DmitriyTSt commented on Lesson_6_Zemskov/app/src/main/java/hh/school/lesson_6_zemskov/PageFragment.kt
> +                arguments = Bundle().apply {
не ошибка, есть еще конструктор bundleOf

2023-11-12 19:16 UTC, DmitriyTSt commented on Lesson_6_Zemskov/app/src/main/java/hh/school/lesson_6_zemskov/ThreeItemFragment.kt
> +                (it as MaterialButton).text = if (binding.fragmentContainerViewPictures.isEmpty()) {
зачем it as 
легче уж binding.buttonShowBanner

2023-11-12 19:16 UTC, DmitriyTSt commented on Lesson_6_Zemskov/app/src/main/java/hh/school/lesson_6_zemskov/adapters/ServiceItemDecoration.kt
> +        val space = parent.context.resources.getDimensionPixelOffset(dimenResId)
лучше в конструктор пиксели подавать, чтобы каждый раз это не резолвить через ресурсы

2023-11-12 19:16 UTC, DmitriyTSt commented on Lesson_6_Zemskov/app/src/main/java/hh/school/lesson_6_zemskov/adapters/ServicesAdapter.kt
> +            ItemServiceBinding.inflate(
тебе не нравится как я показывал ? подавать только parent внутрь
вьюха ведь привязана к самому вью холдеру
представь, что ты его будешь переиспользовать в другом адаптере, тебе придется это закопипастить

2023-11-12 19:16 UTC, DmitriyTSt commented on Lesson_6_Zemskov/app/src/main/java/hh/school/lesson_6_zemskov/model/Service.kt
> +    @get:DrawableRes val iconResId: Int
зачем get: ?

2023-11-12 19:16 UTC, DmitriyTSt commented on Lesson_6_Zemskov/app/src/main/res/layout/fragment_page.xml
> +    <com.google.android.material.card.MaterialCardView
а зачем карточка ?

2023-11-12 19:16 UTC, DmitriyTSt commented on Lesson_6_Zemskov/app/src/main/res/layout/fragment_page.xml
> +    <com.google.android.material.card.MaterialCardView
для клика, понял

2023-11-12 19:16 UTC, DmitriyTSt commented on Lesson_6_Zemskov/app/src/main/res/values/strings.xml
> +    <string name="helper_message">Показания сданы &lt;b>%s&lt;/b> и будут учтены при следующем расчете &lt;b>%s&lt;/b></string>
так как ты это форматом вставляешь, то наверное можно еще присмотреться к SpannableString, html это такой, крайний вариант, не особо нативный )

2023-11-12 19:24 UTC, KochevniKXXI commented on Lesson_6_Zemskov/app/src/main/java/hh/school/lesson_6_zemskov/MainActivity.kt
> +        binding.toolbar.title =
Рассматривал этот вариант. Но так как тубар везде типовой решил попробовать таким образом.

2023-11-12 19:25 UTC, KochevniKXXI commented on Lesson_6_Zemskov/app/src/main/java/hh/school/lesson_6_zemskov/MainActivity.kt
> +    fun addMenu(
Про интерфейс понял.

2023-11-12 19:29 UTC, KochevniKXXI commented on Lesson_6_Zemskov/app/src/main/java/hh/school/lesson_6_zemskov/model/Service.kt
> +    @get:DrawableRes val iconResId: Int
Без него ошибка была. Перепроверю

2023-11-12 19:32 UTC, KochevniKXXI commented on Lesson_6_Zemskov/app/src/main/res/layout/fragment_page.xml
> +    <com.google.android.material.card.MaterialCardView
Да, чтобы с анимацией состояний не заморачиваться

2023-11-12 19:34 UTC, KochevniKXXI commented on Lesson_6_Zemskov/app/src/main/res/values/strings.xml
> +    <string name="helper_message">Показания сданы &lt;b>%s&lt;/b> и будут учтены при следующем расчете &lt;b>%s&lt;/b></string>
Форматирование spannable и annotation тоже смотрел

2023-11-13 06:08 UTC, KochevniKXXI commented on Lesson_6_Zemskov/app/src/main/java/hh/school/lesson_6_zemskov/model/Service.kt
> +    @get:DrawableRes val iconResId: Int
да, ошибка. This annotation is not applicable to target 'member property without backing field or delegate'

2023-11-13 07:12 UTC, DmitriyTSt approved these changes

2023-11-13 07:55 UTC, merged