lesson7
KochevniKXXI/h-h-school pull request #6
Opened 2023-11-16 10:00 UTC by KochevniKXXI

2023-11-22 19:15 UTC, DmitriyTSt requested changes

2023-11-22 19:15 UTC, DmitriyTSt commented on Lesson_7_Zemskov/app/src/main/java/hh/school/lesson_7_zemskov/data/BridgesApiService.kt
> +    @GET("bridges/{id}")
я чет даже забыл что он есть, забавно

2023-11-22 19:15 UTC, DmitriyTSt commented on Lesson_7_Zemskov/app/src/main/java/hh/school/lesson_7_zemskov/extensions/Extensions.kt
> +fun List<Divorce>.asString(): String {
я бы наверное все таки у моста сделал экст такой

2023-11-22 19:15 UTC, DmitriyTSt commented on Lesson_7_Zemskov/app/src/main/java/hh/school/lesson_7_zemskov/ui/DetailsBridgeFragment.kt
> +                    ARG_BRIDGE_DIVORCES to bridgeDivorces.toTypedArray()
если ты мост по айдишнику грузишь, зачем передавать список этот ?

2023-11-22 19:15 UTC, DmitriyTSt commented on Lesson_7_Zemskov/app/src/main/java/hh/school/lesson_7_zemskov/ui/DetailsBridgeFragment.kt
> +            parentFragmentManager.popBackStack()
тут я говорил что лучше чтобы навигацией управлял внешний объект, в котором навигация проходит через абстракцию

2023-11-22 19:15 UTC, DmitriyTSt commented on Lesson_7_Zemskov/app/src/main/java/hh/school/lesson_7_zemskov/ui/DetailsBridgeFragment.kt
> +    private fun loadBridge(id: Int) {
я бы точно побил на методы это
слишком большой метод
можно вынести bindBridge, bindError

2023-11-22 19:15 UTC, DmitriyTSt commented on Lesson_7_Zemskov/app/src/main/java/hh/school/lesson_7_zemskov/ui/ListBridgesFragment.kt
> +                parentFragmentManager.commit {
навигация через интерфейс

2023-11-22 19:15 UTC, DmitriyTSt commented on Lesson_7_Zemskov/app/src/main/java/hh/school/lesson_7_zemskov/ui/MainActivity.kt
> +        enableEdgeToEdge(
прикольно, в школе сам много нового узнаю)

2023-11-22 19:15 UTC, DmitriyTSt commented on Lesson_7_Zemskov/app/src/main/res/layout/fragment_details_bridge.xml
> +        android:stateListAnimator="@animator/bridge_app_bar_state_list_animator">
как будто должно быть наоборот, тень в свернутом, а развернутый без тени, и это просто лифтом решается

2023-11-22 19:15 UTC, DmitriyTSt commented on Lesson_7_Zemskov/app/src/main/res/layout/fragment_details_bridge.xml
> +        android:layout_height="match_parent"
если будет много контента, наползет на кнопку

2023-11-22 19:18 UTC, KochevniKXXI commented on Lesson_7_Zemskov/app/src/main/java/hh/school/lesson_7_zemskov/ui/DetailsBridgeFragment.kt
> +                    ARG_BRIDGE_DIVORCES to bridgeDivorces.toTypedArray()
Если грузить по id, то там это поле null, так что приходится его тоже передавать

2023-11-23 10:39 UTC, KochevniKXXI commented on Lesson_7_Zemskov/app/src/main/res/layout/fragment_details_bridge.xml
> +        android:stateListAnimator="@animator/bridge_app_bar_state_list_animator">
В фигме так нарисовано: развёрнутый с тенью. Поэтому лифт, как я понял не подойдёт. Он же именно поднимает при скроле, а мне опустить нужно

2023-11-23 10:39 UTC, KochevniKXXI commented on Lesson_7_Zemskov/app/src/main/res/layout/fragment_details_bridge.xml
> +        android:layout_height="match_parent"
Проверил. Не наползает. Кнопка выше

2023-11-23 18:08 UTC, merged