lesson8
KochevniKXXI/h-h-school pull request #8
Opened 2023-11-20 19:37 UTC by KochevniKXXI

2023-11-22 19:40 UTC, DmitriyTSt requested changes
1. Заголовок не является обязательно в задании написано, у меня заметка не сохранилась без заголовка
2. нажал выйти при открытой клавиатуре - краш два раза
<img width="1137" alt="Снимок экрана 2023-11-22 в 23 21 38" src="https://github.com/KochevniKXXI/h-h-school/assets/12156501/14b899f2-608f-41ea-be04-876ea44130f1">
3. раскрытый поиск не белый

2023-11-22 19:40 UTC, DmitriyTSt commented on Lesson_8_Zemskov/app/src/main/java/hh/school/lesson_8_zemskov/ui/MainActivity.kt
> +    override fun startNoteEditorFragment(noteId: String?) {
возможно лучше чтобы тут фрагмент был - можно переиспользовать для других навигаций (вдруг третий экран)

2023-11-22 19:40 UTC, DmitriyTSt commented on Lesson_8_Zemskov/app/src/main/java/hh/school/lesson_8_zemskov/ui/list_notes/ListNotesFragment.kt
> +            (actionView as SearchView).apply {
apply лишний, для одной штуки лучше не надо писать, усложнение и лишняя ступенька

2023-11-22 19:40 UTC, DmitriyTSt commented on Lesson_8_Zemskov/app/src/main/java/hh/school/lesson_8_zemskov/ui/list_notes/NoteActionsDialogFragment.kt
> +            .setPositiveButton(getString(R.string.button_delete_text), listener)
там есть метод для resId, не обязательно getString делать

2023-11-22 19:40 UTC, DmitriyTSt commented on Lesson_8_Zemskov/app/src/main/java/hh/school/lesson_8_zemskov/ui/list_notes/ListNotesFragment.kt
> +                            infoBinding.textViewMessage.visibility = View.VISIBLE
давай изучим экст isVisible

2023-11-22 19:40 UTC, DmitriyTSt commented on Lesson_8_Zemskov/app/src/main/java/hh/school/lesson_8_zemskov/ui/list_notes/adapter/NoteViewHolder.kt
> +            if (note.title.isNotBlank()) {
ой ой ой, ctrl alt L

2023-11-22 19:40 UTC, DmitriyTSt commented on Lesson_8_Zemskov/app/src/main/java/hh/school/lesson_8_zemskov/ui/list_notes/adapter/NoteViewHolder.kt
> +                        if (note.color == resources.getColor(R.color.white)) {
тут все в депрекейтах, причем студия говорит как исправить можно быстро

2023-11-22 19:40 UTC, DmitriyTSt commented on Lesson_8_Zemskov/app/src/main/java/hh/school/lesson_8_zemskov/ui/list_notes/ListNotesFragment.kt
> +                    infoBinding.circularProgressIndicator.hide()
вот где то тут краш, давай поставим не lifecycleScope а viewLifecycleOwner.lifecycleScope, краш должен уйти (чтобы подписка была активна только в рамках ЖЦ вьюхи, а не фрагмента всего)

2023-11-22 19:40 UTC, DmitriyTSt commented on Lesson_8_Zemskov/app/src/main/java/hh/school/lesson_8_zemskov/ui/note_editor/NoteEditorFragment.kt
> +                binding.toolbar.setNavigationOnClickListener {
вот это по идее можно вынести из коллекта, он ничего не использует из него

2023-11-22 19:40 UTC, DmitriyTSt commented on Lesson_8_Zemskov/app/src/main/java/hh/school/lesson_8_zemskov/ui/note_editor/NoteEditorFragment.kt
> +        _binding = null
лучше такие штуки делать до super

2023-11-22 19:40 UTC, DmitriyTSt commented on Lesson_8_Zemskov/app/src/main/res/values/styles.xml
> +        <item name="lineHeight">28dp</item>
а lineHeight на всех андроидах работает версиях? просто интересно

2023-11-23 10:43 UTC, KochevniKXXI commented on Lesson_8_Zemskov/app/src/main/res/values/styles.xml
> +        <item name="lineHeight">28dp</item>
как я понял да, есть еще android:lineHeight он только с 28api

2023-11-23 18:08 UTC, merged